name: CI ReOrder

on:
  push:
    branches: [ dev, master, release ]
  pull_request:
    branches: [ dev, master, release ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      # Maven se encarga de construir, iniciar app, testear (Karate), detener app
      - name: Construir y Testear con Maven
        run: mvn -B verify # Este comando orquesta todo (se paso la lógica al pom.xml)

      # Subir el JAR (solo si todo fue bien)
      - name: Subir JAR
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: spring-boot-app
          path: target/*.jar
